### ISSUE TITLE
error happend on QT

### ISSUE THREAD

**Issue by ChenyangRan** [gthd/Reinforcement_Learning#1]
Hi, some error happends when I run your code.
I have test my vrep3.6.2, and it seems ok.
I run your code by anaconda. Could you please help me?
The error is that:
![6A8399CV8$0 7UU~16QZ@EQ](https://user-images.githubusercontent.com/29306735/75351272-d81f3b00-58e2-11ea-809f-8dbb912467e5.png)

**Comment by gthd** [comment]
What OS you are using ?

**Comment by gthd** [comment]
If on Linux then run:
sudo apt-get install libxkbcommon-x11-dev
export PATH=$PATH:~/Qt/Tools/QtCreator/bin

**Comment by ChenyangRan** [comment]
> If on Linux then run:
> sudo apt-get install libxkbcommon-x11-dev
> export PATH=$PATH:~/Qt/Tools/QtCreator/bin

Thanks for your reply, I'll try it.
Thanks you again.
